package ai.elimu.appstore.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import ai.elimu.appstore.model.Application;

import ai.elimu.appstore.dao.ApplicationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig applicationDaoConfig;

    private final ApplicationDao applicationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        applicationDaoConfig = daoConfigMap.get(ApplicationDao.class).clone();
        applicationDaoConfig.initIdentityScope(type);

        applicationDao = new ApplicationDao(applicationDaoConfig, this);

        registerDao(Application.class, applicationDao);
    }
    
    public void clear() {
        applicationDaoConfig.clearIdentityScope();
    }

    public ApplicationDao getApplicationDao() {
        return applicationDao;
    }

}
