package ai.elimu.appstore.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import ai.elimu.appstore.model.Application;
import ai.elimu.appstore.model.project.AppCategory;
import ai.elimu.appstore.model.project.AppGroup;
import ai.elimu.appstore.model.ApplicationVersion;

import ai.elimu.appstore.dao.ApplicationDao;
import ai.elimu.appstore.dao.AppCategoryDao;
import ai.elimu.appstore.dao.AppGroupDao;
import ai.elimu.appstore.dao.ApplicationVersionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig applicationDaoConfig;
    private final DaoConfig appCategoryDaoConfig;
    private final DaoConfig appGroupDaoConfig;
    private final DaoConfig applicationVersionDaoConfig;

    private final ApplicationDao applicationDao;
    private final AppCategoryDao appCategoryDao;
    private final AppGroupDao appGroupDao;
    private final ApplicationVersionDao applicationVersionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        applicationDaoConfig = daoConfigMap.get(ApplicationDao.class).clone();
        applicationDaoConfig.initIdentityScope(type);

        appCategoryDaoConfig = daoConfigMap.get(AppCategoryDao.class).clone();
        appCategoryDaoConfig.initIdentityScope(type);

        appGroupDaoConfig = daoConfigMap.get(AppGroupDao.class).clone();
        appGroupDaoConfig.initIdentityScope(type);

        applicationVersionDaoConfig = daoConfigMap.get(ApplicationVersionDao.class).clone();
        applicationVersionDaoConfig.initIdentityScope(type);

        applicationDao = new ApplicationDao(applicationDaoConfig, this);
        appCategoryDao = new AppCategoryDao(appCategoryDaoConfig, this);
        appGroupDao = new AppGroupDao(appGroupDaoConfig, this);
        applicationVersionDao = new ApplicationVersionDao(applicationVersionDaoConfig, this);

        registerDao(Application.class, applicationDao);
        registerDao(AppCategory.class, appCategoryDao);
        registerDao(AppGroup.class, appGroupDao);
        registerDao(ApplicationVersion.class, applicationVersionDao);
    }
    
    public void clear() {
        applicationDaoConfig.clearIdentityScope();
        appCategoryDaoConfig.clearIdentityScope();
        appGroupDaoConfig.clearIdentityScope();
        applicationVersionDaoConfig.clearIdentityScope();
    }

    public ApplicationDao getApplicationDao() {
        return applicationDao;
    }

    public AppCategoryDao getAppCategoryDao() {
        return appCategoryDao;
    }

    public AppGroupDao getAppGroupDao() {
        return appGroupDao;
    }

    public ApplicationVersionDao getApplicationVersionDao() {
        return applicationVersionDao;
    }

}
